version: '3.2'

services:
  node:
    environment:
      - NODE_ENV=test
      - COVERALLS_SERVICE_NAME=travis-ci
      - CI
      - COVERALLS_REPO_TOKEN
    command: bin/test.sh
  postgres:
    volumes:
      - test_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=realworld_test

volumes:
  test_data: