version: '3.2'

services:
  node:
    environment:
      - NODE_ENV=development
  postgres:
    volumes:
      - development_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=realworld_development

volumes:
  development_data: