version: '3.2'

services:
  node:
    build: .
    image: node
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment:
      - DB_HOST=postgres
      - SECRET=secret
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  postgres:
    image: postgres:10.3
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=realworld