version: '3.2'

services:
  node:
    build: .
    image: node
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment:
      - DB_HOST=postgres
      - SECRET=secret
    command: >
      bash -c "yarn knex migrate:latest &&
               yarn start"
  postgres:
    image: postgres:10.3
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=realworld