version: '3.2'

services:
  node:
    build: .
    image: node
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment:
      - DB_HOST=postgres
  postgres:
    image: postgres:10.3-alpine
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=realworld
      - POSTGRES_DB=realworld_development

volumes:
  data: