name: Deploy

on:
  push:
    branches: [main]
  # специальное событие, которое происходит при ручном вызове workflow
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_KNOWN_HOSTS }} >> ~/.ssh/known_hosts
      - name: Copy files to the server
        # заливаем файлы при помощи rsync
        run: |
          rsync -a --progress --human-readable --delete \
          --exclude-from '.gitignore' \
          --exclude .gitignore \
          --exclude .git \
          . deploy@172.104.151.230:~/realworld/
      # job для перезапуска приложения при помощи pm2
      - name: Restart the application
        run: |
          ssh deploy@172.104.151.230 "pushd ~/realworld && npm install && popd && pm2 restart realworld"
